### ISSUE TITLE
Update for Pygame Zero 1.2

### ISSUE THREAD

**Issue by lordmauve** [RPi-Distro/pgzero#1]
Pygame Zero 1.2 has been released.

Additionally, the repository is now located at https://github.com/lordmauve/pgzero/

**Comment by XECDesign** [comment]
Thanks for the heads up. Would you like a PR for the debian/ files after they're updated or would you prefer to keep them separate?

**Comment by XECDesign** [comment]
The new version should hit the repo soon.
